### ISSUE TITLE
Telegram Bot: auto configuration exeption

### ISSUE THREAD

**Issue by kyberorg** [yadevee/yals#108]
Every startup we have 
`
2019-09-12 11:02:20.965 ERROR 6 --- [           main] e.y.configuration.TelegramBotAutoConfig  : [TelegramAutoConfig] Failed to register bot,
	... 36 common frames omitted,
,
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error removing old webhook,
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:25) ~[telegrambots-4.4.0.1.jar!/:na],
	at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:79) ~[telegrambots-4.4.0.1.jar!/:na],
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212],
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212],
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212],
	at org.telegram.telegrambots.meta.TelegramBotsApi.registerBot(TelegramBotsApi.java:120) ~[telegrambots-meta-4.4.0.1.jar!/:na],
	at ee.yals.configuration.TelegramBotAutoConfig.start(TelegramBotAutoConfig.java:56) ~[classes!/:2.4],
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212],
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE],
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE],
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE],
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE],
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE],
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE],
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE],
	at ee.yals.YalsApplication.main(YalsApplication.java:13) ~[classes!/:2.4],
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[yals.jar:2.4],
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[yals.jar:2.4],
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[yals.jar:2.4],
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[yals.jar:2.4],
Caused by: org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error deleting webhook,
	at org.telegram.telegrambots.meta.api.methods.updates.DeleteWebhook.deserializeResponse(DeleteWebhook.java:39) ~[telegrambots-meta-4.4.0.1.jar!/:na],
	at org.telegram.telegrambots.meta.api.methods.updates.DeleteWebhook.deserializeResponse(DeleteWebhook.java:18) ~[telegrambots-meta-4.4.0.1.jar!/:na],
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:715) ~[telegrambots-4.4.0.1.jar!/:na],
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:47) ~[telegrambots-meta-4.4.0.1.jar!/:na],
	at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:74) ~[telegrambots-4.4.0.1.jar!/:na]`

**Comment by kyberorg** [comment]
Fixed in #109
